export const ProfilesActionTypes = {
    FETCH_ALL_ARTIST_START: 'FETCH_ALL_ARTIST_START',
    FETCH_ALL_ARTIST_SUCCESS: 'FETCH_ALL_ARTIST_SUCCESS',
    FETCH_ALL_ARTIST_FAILURE: 'FETCH_ALL_ARTIST_FAILURE',
}